#ifndef _GLOBAL_H
#define _GLOBAL_H 

/**
 * Defines the current state of the system.
 */
typedef enum _state
{
	RED_S,
	YELLOW_S,
    	GREEN_S
} state_t;

/**
 * All the different event that can be generated by the buttons. 
 */
typedef enum {
	STOP_EVT = 0,
    	GO_EVT = 1, 
    	NO_EVT = 2
} PinEvent_t;

/**
 * @brief Returns one button event from the pin listener module
 * 
 * @return PinEvent_t 
 */
PinEvent_t getButtonEvent(void);

/**
 * @brief Get the global state. This must be thread safe!
 * 
 * @return state_t 
 */
state_t getState(void);

/**
 * @brief Set the global state to newState. This must be thread safe!
 * 
 * @param newState 
 */
void setState(state_t newState);

#endif /* _GLOBAL_H */
